name: LoA
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.0
  - pip
  - libmagic
  - poppler
  - tesseract
  - pandoc
  - libxml2
  - libxslt
  - rust
  - cython
  - pip:
    - unstructured[local-inference]
    - scrapy
    - spacy
    - tqdm
    - paperscraper
    - sentence_transformers
    - torch
    - torchvision
    - torchaudio
    - opencv-python
    - paddleocr
    - transformers
    - snorkel
    - pandas
    - numpy
    - beautifulsoup4
    - requests
    - selenium
    - webdriver_manager
    - pdfminer.six
    - sentencepiece
